Repository lemma-osu/sknnr, pull requests merged in 2023-05, with the labels that each got.

#11 pyproject.toml
  .github/workflows/ci.yaml
  README.md
  pyproject.toml
  setup.py
  src/sklearn_knn/__about__.py
  src/sklearn_knn/__init__.py
Labels: dx

#14 Subclass estimators from KNeighborsRegressor
  src/sklearn_knn/_base.py
  src/sklearn_knn/_euclidean.py
  src/sklearn_knn/_gnn.py
  src/sklearn_knn/_mahalanobis.py
  src/sklearn_knn/_raw.py
  tests/test_estimators.py
  tests/test_port.py
Labels: testing, estimator

#25 Remove TransformedKNeighborsMixin.predict to avoid double transformation
  src/sknnr/_base.py
Labels: bug

#27 Implementation of Most Similar Neighbor (MSN)
  pyproject.toml
  src/sknnr/_msn.py
  src/sknnr/transformers/__init__.py
  src/sknnr/transformers/_ccora.py
  src/sknnr/transformers/_ccora_transformer.py
  tests/conftest.py
  tests/data/msn_moscow_ref_distances_k5.csv
  tests/data/msn_moscow_ref_neighbors_k5.csv
  tests/data/msn_moscow_trg_distances_k5.csv
  tests/data/msn_moscow_trg_neighbors_k5.csv
  tests/test_estimators.py
  tests/test_port.py
Labels: enhancement, estimator

#32 Test all estimators' predict method for Moscow test data
  tests/conftest.py
  tests/data/euclidean_moscow_trg_predicted_unweighted_k5.csv
  tests/data/euclidean_moscow_trg_predicted_weighted_k5.csv
  tests/data/gnn_moscow_trg_predicted_unweighted_k5.csv
  tests/data/gnn_moscow_trg_predicted_weighted_k5.csv
  tests/data/mahalanobis_moscow_trg_predicted_unweighted_k5.csv
  tests/data/mahalanobis_moscow_trg_predicted_weighted_k5.csv
  tests/data/msn_moscow_trg_predicted_unweighted_k5.csv
  tests/data/msn_moscow_trg_predicted_weighted_k5.csv
  tests/data/raw_moscow_trg_predicted_unweighted_k5.csv
  tests/data/raw_moscow_trg_predicted_weighted_k5.csv
  tests/test_port.py
Labels: testing, estimator
