Repository lemma-osu/sknnr, pull requests merged in 2023-09, with the labels that each got.

#46 Add R6 southwest Oregon (SWO) Ecology dataset
  src/sknnr/datasets/__init__.py
  src/sknnr/datasets/_base.py
  src/sknnr/datasets/data/swo_ecoplot_env.csv
  src/sknnr/datasets/data/swo_ecoplot_spp.csv
  tests/test_datasets.py
Labels: testing

#48 Store repeatedly used variables as estimator attributes #47
  src/sknnr/_base.py
  src/sknnr/transformers/_cca_transformer.py
  src/sknnr/transformers/_ccora_transformer.py
Labels: bug, estimator

#50 Implement independent `predict` and `score` methods for all estimators
  src/sknnr/__init__.py
  src/sknnr/_base.py
  src/sknnr/_euclidean.py
  src/sknnr/_gnn.py
  src/sknnr/_mahalanobis.py
  src/sknnr/_msn.py
  src/sknnr/_raw.py
  tests/data/euclidean_moscow_ref_predicted_unweighted_k5.csv
  tests/data/euclidean_moscow_ref_predicted_weighted_k5.csv
  tests/data/gnn_moscow_ref_distances_k5_c3.csv
  tests/data/gnn_moscow_ref_predicted_unweighted_k5.csv
  tests/data/gnn_moscow_ref_predicted_unweighted_k5_c3.csv
  tests/data/gnn_moscow_ref_predicted_weighted_k5.csv
  tests/data/gnn_moscow_ref_predicted_weighted_k5_c3.csv
  tests/data/gnn_moscow_trg_distances_k5_c3.csv
  tests/data/gnn_moscow_trg_predicted_unweighted_k5_c3.csv
  tests/data/gnn_moscow_trg_predicted_weighted_k5_c3.csv
  tests/data/mahalanobis_moscow_ref_predicted_unweighted_k5.csv
  tests/data/mahalanobis_moscow_ref_predicted_weighted_k5.csv
  tests/data/msn_moscow_ref_distances_k5_c3.csv
  tests/data/msn_moscow_ref_predicted_unweighted_k5.csv
  tests/data/msn_moscow_ref_predicted_unweighted_k5_c3.csv
  tests/data/msn_moscow_ref_predicted_weighted_k5.csv
  tests/data/msn_moscow_ref_predicted_weighted_k5_c3.csv
  tests/data/msn_moscow_trg_distances_k5_c3.csv
  tests/data/msn_moscow_trg_predicted_unweighted_k5_c3.csv
  tests/data/msn_moscow_trg_predicted_weighted_k5_c3.csv
  tests/data/raw_moscow_ref_predicted_unweighted_k5.csv
  tests/data/raw_moscow_ref_predicted_weighted_k5.csv
  tests/datasets.py
  tests/test_port.py
Labels: enhancement, estimator

#52 Refactor transformed estimators
  src/sknnr/_base.py
  src/sknnr/_euclidean.py
  src/sknnr/_gnn.py
  src/sknnr/_mahalanobis.py
  src/sknnr/_msn.py
Labels: refactor, estimator

#54 Test `y_fit` functionality
  tests/test_estimators.py
Labels: testing, estimator

#56 Only store array-like `dataframe_index_in_` and fix `CCA` compability with `list`
  src/sknnr/_base.py
  src/sknnr/transformers/_cca_transformer.py
  tests/test_estimators.py
Labels: bug
