Repository lemma-osu/sknnr, pull requests merged in 2024-07, with the labels that each got.

#70 Fix `r2_score` port test
  .github/workflows/ci.yaml
  tests/test_port.py
Labels: bug

#69 Expose functions from `datasets` module in public API
  src/sknnr/datasets/__init__.py
  src/sknnr/datasets/_base.py
  tests/test_datasets.py
Labels: enhancement

#73 Update `hatch version` guide
  docs/pages/contributing.md
Labels: documentation

#75 Specify all `__init__` params for MSN and GNN
  src/sknnr/_base.py
  src/sknnr/_gnn.py
  src/sknnr/_msn.py
  tests/test_estimators.py
Labels: bug
